# Generated by Django 5.0.2 on 2024-02-18 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mail_id', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic_path', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('du', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_unit.deliveryunit')),
            ],
        ),
    ]
