# Generated by Django 5.0.2 on 2024-02-23 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_unit', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='du',
            new_name='du_id',
        ),
        migrations.CreateModel(
            name='DeliveryUnitMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('du_head_id', models.ForeignKey(blank=True, db_column='du_head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_head_id', to='employee.employee')),
                ('du_id', models.ForeignKey(db_column='du_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery_unit.deliveryunit')),
                ('hrbp_id', models.ForeignKey(blank=True, db_column='hrbp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrbp_id', to='employee.employee')),
            ],
        ),
    ]
