# Generated by Django 5.0.2 on 2024-02-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_unit', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Initiated_by_PM'), (2, 'approved_by_DUHEAD'), (3, 'Completed'), (4, 'Rejected'), (5, 'Cancelled')], default=1)),
                ('rejection_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('currentdu_id', models.ForeignKey(db_column='currentdu_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdu', to='delivery_unit.deliveryunit')),
                ('employee_id', models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('initiated_by', models.ForeignKey(db_column='initiated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_by', to='employee.employee')),
                ('newpm_id', models.ForeignKey(db_column='newpm_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newpm_id', to='employee.employee')),
                ('targetdu_id', models.ForeignKey(db_column='targetdu_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdu', to='delivery_unit.deliveryunit')),
            ],
        ),
        migrations.CreateModel(
            name='TransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_band', models.IntegerField(choices=[('A1', 'level1'), ('A2', 'level2'), ('B1', 'level3'), ('B2', 'level4'), ('C1', 'level5')], default=1)),
                ('total_experience', models.IntegerField()),
                ('experion_experience', models.IntegerField()),
                ('employee_skills', models.TextField(blank=True, max_length=200, null=True)),
                ('upskilling_suggestions', models.TextField(blank=True, max_length=200, null=True)),
                ('strengths', models.TextField(blank=True, max_length=200, null=True)),
                ('areas_of_improvement', models.TextField(blank=True, max_length=200, null=True)),
                ('additional_training_needs', models.TextField(blank=True, max_length=200, null=True)),
                ('releaseReason', models.TextField(blank=True, max_length=200, null=True)),
                ('transfer_id', models.ForeignKey(db_column='transfer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='transfer.transfer')),
            ],
        ),
    ]
