# Generated by Django 5.0.2 on 2024-02-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='new_pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmassigned', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeetransfers', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='transfer.transfer'),
        ),
    ]
