# Generated by Django 5.0.2 on 2024-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated_by_PM'), (2, 'approved_by_DUHEAD'), (3, 'Completed'), (4, 'Rejected'), (5, 'Cancelled')]),
        ),
    ]
