# Generated by Django 5.0.2 on 2024-02-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transferdetails_transfer'),
        ('transfer', '0002_transfer_new_pm_alter_transfer_employee_and_more'),
    ]

    operations = [
    ]
