# Generated by Django 5.0.2 on 2024-02-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transfer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferdetails',
            old_name='transfer_id',
            new_name='transfer',
        ),
    ]
