# Generated by Django 5.0.2 on 2024-02-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_rename_transfer_id_transferdetails_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='transfer.transfer'),
        ),
    ]
