# Generated by Django 5.0.2 on 2024-02-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_transferdetails_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer',
            field=models.ForeignKey(db_column='transfer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='transfer.transfer'),
        ),
        migrations.RenameField(
            model_name='transferdetails',
            old_name='transfer',
            new_name='transfer_id',
        ),
        migrations.RemoveField(
            model_name='transferdetails',
            name='total_experience',
        ),
    ]
