# Generated by Django 5.0.2 on 2024-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_alter_transferdetails_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='total_experience',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
