# Generated by Django 5.0.2 on 2024-02-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_transferdetails_total_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer_id',
            field=models.OneToOneField(db_column='transfer_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transfer.transfer'),
        ),
    ]
