# Generated by Django 5.0.2 on 2024-02-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_alter_transferdetails_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer_id',
            field=models.OneToOneField(blank=True, db_column='transfer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transfer.transfer'),
        ),
    ]
