# Generated by Django 5.0.2 on 2024-02-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_transfer_new_pm_alter_transfer_employee_and_more'),
        ('transfer', '0012_alter_transferdetails_transfer_id'),
    ]

    operations = [
    ]
